### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by Nakamcode** [AccessibleForAll/Support#163]
### Website URL

https://nakam360.netlify.app/

### GitHub Repo URL

https://github.com/Nakamcode/Portfolio-website/

**Comment by EmmaDawsonDev** [comment]
Hi Nakam! I'm hoping to get to this soon but I got a cold and lost my voice so haven't been able to record a video yet.

**Comment by Nakamcode** [comment]
Alright, I wish you fast recovery

**Comment by EmmaDawsonDev** [comment]
Sorry for the delay! October was a bit busy - I hope this is helpful, it'll go live tonight at 7pm GMT. [Youtube video](https://youtu.be/_fFd2NKeY5A) 

Overall, the main things to fix are color contrast, not nesting buttons inside links, making sure your hamburger menu is keyboard accessible and checking the order of your heading levels.
