### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by samuelbarrionuevo** [AccessibleForAll/Support#190]
### Name

ericbarrionuevo

**Comment by EmmaDawsonDev** [comment]
Hi @samuelbarrionuevo your membership in the organisation went through automatically. It shows you are a member in the Organizations section of your profile:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/57045550/194761427-b5103af1-bb8f-4158-907a-3da74bea1d05.png">
