### ISSUE TITLE
feat: Add steps to join organization on public homepage 

### ISSUE THREAD

**Issue by anthonychinwe** [AccessibleForAll/Support#22]
It would be helpful if the steps required to join the organization were indicated on the organization's `public` homepage. 
These steps could include a link to the invitation `Issues` template in the `Support` repo.

**Comment by emmalearnscode** [comment]
That sounds like a great idea! Did you want to go ahead and add that or shall I?

**Comment by anthonychinwe** [comment]
> That sounds like a great idea! Did you want to go ahead and add that or shall I?

Sure, I can add it

**Comment by emmalearnscode** [comment]
Added in https://github.com/AccessibleForAll/.github/commit/070673e679cf3dab867fb1af25147302077891b0 Thanks so much for contributing!
