### ISSUE TITLE
[DOCS] Empty Readme file

### ISSUE THREAD

**Issue by CBID2** [AccessibleForAll/Support#238]
Hi @EmmaDawsonDev! I noticed that [this file](https://github.com/AccessibleForAll/Support/blob/main/CONTRIBUTING.md) is empty, so I was wondering if there was anything in particular that you wanted in there.

**Comment by EmmaDawsonDev** [comment]
Well spotted. There's probably no need for instructions on how to contribute to the support repo itself as it doesn't really have that function but it might be nice to point people to the different projects in the organisation and how to contribute to each one.

**Comment by CBID2** [comment]
> Well spotted. There's probably no need for instructions on how to contribute to the support repo itself as it doesn't really have that function but it might be nice to point people to the different projects in the organisation and how to contribute to each one.
Good point @EmmaDawsonDev! I'm going to write some stuff on a Google Doc and post the link on here for your feedback before putting it on the file. How does that sound?

**Comment by EmmaDawsonDev** [comment]
Sounds great 👍🏻
