### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by JayantGoel001** [AccessibleForAll/Support#27]
### Website URL

https://jayantgoel001.github.io/

### GitHub Repo URL

https://github.com/JayantGoel001/JayantGoel001.github.io

**Comment by JayantGoel001** [comment]
@emmalearnscode

**Comment by emmalearnscode** [comment]
Hello! Thank you so much for requesting a review. I am hoping to get some time to look at your site properly tomorrow.

**Comment by JayantGoel001** [comment]
> Hello! Thank you so much for requesting a review. I am hoping to get some time to look at your site properly tomorrow.

Hi @emmalearnscode,
Ya sure No Prob😃😄
