### ISSUE TITLE
Contribution file is empty.

### ISSUE THREAD

**Issue by E-fais** [AccessibleForAll/Support#327]
Hi, the contribution.md file is empty.  Could you please give me an idea about this organization.

**Comment by EmmaDawsonDev** [comment]
I guess you didn’t arrive here via the front page? If not, how did you find the org? Would be good to know where to add additional information 

![C674E626-D391-4E3E-AE8C-43C40F51491F](https://user-images.githubusercontent.com/57045550/219968506-4ecc2058-dae8-49bc-abe5-fcf86904739e.png)

**Comment by E-fais** [comment]
![Support_CONTRIBUTING md at main · AccessibleForAll_Support - Google Chrome 20-02-2023 8 25 36 PM](https://user-images.githubusercontent.com/102040088/220169783-5e5c2999-07be-4720-bafe-1604f6284aa4.png)
This is what i see. I have seen name of  this organization on one user's profile and clicked the link.

**Comment by EmmaDawsonDev** [comment]
Thanks, that’s good to know. I’ll put it on my list to add some extra information

**Comment by E-fais** [comment]
I would like to contribute to your projects , please let me know the updates when you fix this issue. Thanks.
