### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by RichardHan0314** [AccessibleForAll/Support#371]
### Name

Richard Han

**Comment by RichardHan0314** [comment]
Hello
I am a full stack developer with 7+ years experience of all kinds of modern javascript frameworks.
I like sharing my knowledge and help other people and learn from them.
Thank you,

**Comment by EmmaDawsonDev** [comment]
Hi Richard! Thanks for joining the organisation. 

Emma
