### ISSUE TITLE
Update invitation workflow

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/Support#420]
The invitation.yml workflow contains a short comment that is sent to people when they join the organisation. This could be extended to be more welcoming and give some options for next steps, like contributing to a project or starting a discussion etc.

**Comment by at-the-vr** [comment]
Hey Emma, just wanted to pitch in this suggestion. How about 

Hi there! Welcome to the Accessible For All community! We're thrilled to have you join us. 🎉
We believe that everyone should have equal access to information across the vast Internet, and we're excited to collaborate together to make that a reality.
To get started, you might want to check out our [Resources ](https://github.com/AccessibleForAll/Resources)repository if you're looking for accessibility-related materials. Or, if you're interested in contributing to our motive, we have a project called [AccessibleWebDev ](https://github.com/AccessibleForAll/AccessibleWebDev)that you can start with.
And that's not all. We're always open to new ideas, so feel free to share your thoughts and questions in our [Discussions Tab](https://github.com/orgs/AccessibleForAll/discussions) or create a new issue on one of our projects.
Welcome once more to Accessible For All. We appreciate your visit!

**Comment by EmmaDawsonDev** [comment]
I love it!

**Comment by EmmaDawsonDev** [comment]
Would you like to be assigned?

**Comment by at-the-vr** [comment]
Ohh i should have mentioned, I would not if that's OK, I believe someone else should have a look at YAML files from a beginner's perspective 😄

**Comment by EmmaDawsonDev** [comment]
That's fine! Thanks anyway for the suggestion and let's see if someone else would like to update it.

**Comment by sunilgknair051** [comment]
Hello, I would be happy to edit the yaml file.  Not my first issue on GitHub but on Accessible For All.

**Comment by EmmaDawsonDev** [comment]
Sure @sunilgknair051 let me know if you need any help.
