### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by shubhamsigdar1** [AccessibleForAll/Support#52]
### Website URL

https://shubhamsigdar.netlify.app/

### GitHub Repo URL

https://github.com/shubhamsigdar/Portfolio

**Comment by EmmaDawsonDev** [comment]
Thanks so much for asking for a review Shubham! I'll add my thoughts as issues on your repo and then the video will be released in a couple of weeks.

**Comment by EmmaDawsonDev** [comment]
The video is available here: https://youtu.be/VhlXFDCQ2GY

**Comment by shubhamsigdar1** [comment]
Thank you Emma
