### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by conermurphy** [AccessibleForAll/Support#57]
### Website URL

https://conermurphy.com/

### GitHub Repo URL

https://github.com/conermurphy/conermurphy.com

**Comment by EmmaDawsonDev** [comment]
Hi Coner! Thanks so much for letting me review your profile! It was really well done and lots of things already work really well. I did find a few things you can make even better and I raised some issues for those. Let me know if I didn't explain something well enough. Here's the video of me exploring your site: https://youtu.be/mti7pNxru8U
