### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by mkubdev** [AccessibleForAll/Support#58]
### Website URL

https://www.mkubdev.xyz/

### GitHub Repo URL

https://github.com/mkubdev/mkubdev.xyz

**Comment by EmmaDawsonDev** [comment]
Thanks for letting me review your site! The [video](https://youtu.be/055dvsgK2vA) will go live tomorrow night at 19.30 CEST - hope it's useful!

**Comment by mkubdev** [comment]
Hi Emma! Just saw your review on Youtube, thank you so much for all your insight ✨🙌 !
I will create some issues from your review and try to fix them.
