### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by murtuzaalisurti** [AccessibleForAll/Support#82]
### Website URL

https://murtuzaalisurti.github.io

### GitHub Repo URL

https://github.com/murtuzaalisurti/murtuzaalisurti.github.io

**Comment by EmmaDawsonDev** [comment]
Hi Murtuza! Sorry for the delay, I just started a new job and needed to get into a new routine to find time for making videos. Now I have had a look at your site and I hope you find the feedback useful. The video is here and it will go live on Sunday at 8pm CEST https://youtu.be/KmTXBK8Dbts

Thanks for letting me take a look and any questions just let me know!

**Comment by murtuzaalisurti** [comment]
Thank you so much Emma! Wonderful points mentioned by you. I didn't even know half of the points you mentioned but I will research them and surely improve the site. While building this site, I used a LOT of javascript that's why the navbar isn't fully accessible because I am using javascript to hop on sections. I haven't touched this website in a year (I built in when I was a newbie) in terms of code so I plan to revamp it completely using new technologies.

Once I revamp my site, please take a look at it once again 😄 
Thanks!

**Comment by MarkusEicher** [comment]
Hi Emma. Hi Murtuza. Interesting review and it was helpful to see how such a page looks from an A11Y perspective. I find it useful for newbies to see what certain page elements look like with tabbing or a screen reader. Thank you for this!
